### ISSUE TITLE
Replace SQL with rails `or`

### ISSUE THREAD

**Issue by ninewise** [ZeusWPI/Tab#1]
Upon release of rails 5, [this line](https://github.com/ZeusWPI/Tab/blob/334054142cd444b1a79f00e587cbcd9d2f39eb8c/app/models/user.rb#L21) of SQL code should be replaced with the [new `or` in rails.](https://github.com/rails/rails/commit/9e42cf019f2417473e7dcbfcb885709fa2709f89)

**Comment by becousae** [comment]
Time to get to work, `or` has been implemented in rails 5 :D

**Comment by NoctuaNivalis** [comment]
:tada:

**Comment by Silox** [comment]
🎉🎉
