### ISSUE TITLE
Let people "ask" money from someone

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/Tab#11]
As someone who needs to give money, it is more convenient to forget it than someone who needs money from that person. It would be nice to let a person who needs money from someone fill in a form wanting to recieve a certain amount of money from a certain person. The next time that person logs in, he recieves a message to accept the transaction. 

Neat additions would be to send a reminder (Slack or email) when such a transaction has been asked.

**Comment by NoctuaNivalis** [comment]
been fixed for ages
