### ISSUE TITLE
Order users by debt on index

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/Tab#123]
The current ordering is not really useful to get a quick overview, ordering by balance is much more useful. I think [this line](https://github.com/ZeusWPI/Tab/blob/master/app/controllers/users_controller.rb#L19) would need to be modified to include a sort by balance (increasing).

**Comment by TomNaessens** [comment]
A sort parameter with clickable table headers would be the cleanest solution I think

**Comment by redfast00** [comment]
If that's not too much work, that would be a good solution indeed. The current table contains ID, username and balance, and I don't yet see any use for sorting by id or username.
