### ISSUE TITLE
Transaction view incorrect

### ISSUE THREAD

**Issue by tivervac** [ZeusWPI/Tab#24]
I just entered a transaction of 5.10€ and it showed up as 5.09€.
![ss 2016-04-22 at 12 22 58](https://cloud.githubusercontent.com/assets/3389524/14726181/98f192f0-0820-11e6-8b78-a37a450a82d4.png)

**Comment by becousae** [comment]
The view is correct. The conversion in the form is incorrect. You did in fact give elo 5.09€.

**Comment by NoctuaNivalis** [comment]
Which means you still owe elo a cent.

**Comment by TomNaessens** [comment]
I'll close this in favor of https://github.com/ZeusWPI/Tab/issues/94 as it describes the issue a bit better.
