### ISSUE TITLE
Slack reminder to 'BETAAL UW FUCKING SCHULDEN'

### ISSUE THREAD

**Issue by rien** [ZeusWPI/Tab#28]
When the balance of an user drops below 0, there should be a regular reminder to pay his/her debts on Slack or via e-mail.
The time between reminders should decrease when the user's debt increases.

I suggest a system like this:

| Debt | How many reminders |
| --- | --- |
| > € 0 | 1 reminder |
| > € 5 | once per week |
| > € 10 | once per day |
| > € 15 | once per hour |
| > € 20 | every minute |
| > € 25 | every second |

**Comment by Iepoev** [comment]
>every second
rip backlog

**Comment by mcbloch** [comment]
--> mattermost

**Comment by Jan-PieterBaert** [comment]
@mcbloch with a bot which posts in `~general`?

**Comment by mcbloch** [comment]
Yeah, with an @all @everyone and a @here

**Comment by Jan-PieterBaert** [comment]
Just to make sure that they and everyone else know

**Comment by mcbloch** [comment]
As per new changes people can no longer go in dept :man_shrugging:

**Comment by wschella** [comment]
All these damn superficial people now!
