### ISSUE TITLE
Case insensitive match for a person

### ISSUE THREAD

**Issue by Jan-PieterBaert** [ZeusWPI/Tab#43]
Match usernames case insensitive in the search bar, this makes searching people easier

**Comment by redfast00** [comment]
Aren't zeus usernames already lowercase?

**Comment by Jan-PieterBaert** [comment]
not all of them

**Comment by ajuvercr** [comment]
Correct me if I'm wrong but this is already fixed. #66

**Comment by ajuvercr** [comment]
I don't understand, it may have been reverted, but on `tab.zeus.gent` it's fixed either way
