### ISSUE TITLE
Enable penning to automate money transfers

### ISSUE THREAD

**Issue by TomNaessens** [ZeusWPI/Tab#62]
As a penning, it would be nice if I could upload a list of bank transfer statements (CSV of Argenta) containing users bank transfers and automatically add the credit to their account.

**Comment by Silox** [comment]
Split up into sub-tasks:

* [ ] everyone should be able to start a new transfer with a given amount of credit, which generates a unique code as well as see a list of their past transfers with their corresponding status: pending, approved, declined
* [ ] a user creating a bank transfer should get detailed instructions how to use the unique code
* [x] a user should then make a bank transfer with the unique code in the "free description" message of their bank account 
* [ ] the penning should be able to 
  * [ ] see a list of transfers and their corresponding statuses
  * [ ] approve and/or decline a transfer manually
  * [ ] upload a CSV bank transfer statement which is being processed automatically
* [ ] users should be notified when a transfer has been approved and/or declined with possibly a given reason
* [ ] the penning should be notified when a user created a transfer

**Comment by Silox** [comment]
From a technical point of view:

* [ ] add a new model: "BankTransfer" with fields:
  * [ ] amount (integer, in cents, > 0, mandatory)
  * [ ] status (enum, possible values: pending, approved, declined, mandatory)
  * [ ] reason (string)
* [ ] add a new page where users can create and manage transfers
  * [ ] form to create a new transfer
  * [ ] table with transfer overview
* [ ] add a new page where the penning can manage transfers
  * [ ] table with transfer overview + management buttons
  * [ ] upload possibility for the csv
