### ISSUE TITLE
Tab has rounding errors

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/Tab#94]
When inputting €9,70 Tab changes the value to €9,69. Tested in safari and chrome.

![image](https://user-images.githubusercontent.com/1470064/170359965-29ad3f39-5bb5-4bdb-ac9b-55d498e143db.png)

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1470064/170359938-ca7e74be-2bdf-4e8a-b270-547b8d54ef1a.png">

**Comment by feliciaan** [comment]
Same problem as #24 which was a Tab error and not a user error

**Comment by TomNaessens** [comment]
Form data is sent correctly to the server, so it's the conversion of there that's iffy:

![image](https://user-images.githubusercontent.com/915130/170362107-7c5c3e9a-0788-4718-b3a7-415eb0dd5c75.png)

**Comment by TomNaessens** [comment]
Fixed in https://github.com/ZeusWPI/Tab/commit/2a8a331404863235b66a6c39743fe21834383ac8, will be fixed when the Rails 7 branch is merged.
