### ISSUE TITLE
Pull out API routes in separate controller

### ISSUE THREAD

**Issue by TomNaessens** [ZeusWPI/Tab#95]
This will clean up the code a bit and allow for easy API versioning when making future changes.

This will change the routes for the API so it will be a breaking change for applications using the API. We can copypaste it first, and then remove the old ones to give the dependent applications a bit of time to migrate.

Applications dependent on the API are:
- [x] Tap: https://github.com/ZeusWPI/Tap/pull/178
- [x] Tabbp: https://github.com/ZeusWPI/Tappb/pull/3
- [ ] Hydra: https://github.com/ZeusWPI/hydra-android/pull/584
- [ ] Penning scripts
- [x] whining @ninewise 's scripts
- [ ] @redfast00 scripts
- ... others?

**Comment by TomNaessens** [comment]
@bobbybobbypangang @FKD13 @mcbloch are you aware of any scripts/applications using the Tab API?

**Comment by bobbybobbypangang** [comment]
My scripts for treasuring bookkeeping request all the transactions for user Zeus. (which takes a while, asking transactions for a given year would be helpful). Those are in the private penning repo, but updating them is very easy and I'll after it when this goes online.

**Comment by niknetniko** [comment]
The hydra app for Android also uses it

**Comment by ninewise** [comment]
My scripts are [not very complicated](https://github.com/ninewise/dotfiles/blob/master/local/bin/zeustab) so I don't really mind you breaking them. I will whine about it though.

**Comment by redfast00** [comment]
Tap also uses the Tab API, it's important this doesn't break

**Comment by redfast00** [comment]
And Haldis does not use the Tab API at the moment (this feature is planned, but has not been implemented yet)

**Comment by TomNaessens** [comment]
PR open in https://github.com/ZeusWPI/Tab/pull/99, on the Rails 7 branch, to be merged and deployed soon(tm).

**Comment by TomNaessens** [comment]
So this accidentally kinda already got merged into master, and it is available.

The new endpoint for API requests is the same as the old one, except the URL is `tap.zeus.gent/api/v1/...`. The implementation _should_ be the same, if you notice any differences, let me know.

I'll remove the old endpoints in about a week as the migration is pretty easy.

For the future, these migrations and API changes will be easier as we can just add a `v2` endpoint where necessary.

**Comment by TomNaessens** [comment]
In case anyone wants to view a preview of the documentation, there's a screenshot here: https://github.com/ZeusWPI/Tab/pull/120

**Comment by TomNaessens** [comment]
https://github.com/ZeusWPI/Tab/pull/128 It's happening 😁
