### ISSUE TITLE
Provide API access to usernames

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/Tab#97]
This would allow autocomplete when creating a transactions.
This data is already available in the HTML, so this shouldn't have any privacy implications.

**Comment by TomNaessens** [comment]
Something like this?

```
GET http://localhost:3000/api/v1/users

[
	{
		"id": 1,
		"name": "Zeus"
	},
	{
		"id": 2,
		"name": "silox"
	},
	{
		"id": 3,
		"name": "j"
	},
	{
		"id": 4,
		"name": "admin"
	},
	{
		"id": 5,
		"name": "blarghblargh"
	},
	{
		"id": 6,
		"name": "blarghblarghblargh"
	},
	{
		"id": 7,
		"name": "testtest"
	}
]
```

**Comment by niknetniko** [comment]
That works

**Comment by TomNaessens** [comment]
PR open in https://github.com/ZeusWPI/Tab/pull/99, on the Rails 7 branch, to be merged and deployed soon(tm).

**Comment by redfast00** [comment]
I'd rather not have Tab-internal ID's in there (if it's not needed to create a transaction), this can only cause confusion.

**Comment by TomNaessens** [comment]
Good point. I'm still on the fence about using usernames to create transactions, but I guess it makes sense here as our usernames are uniquely defined. I'll leave them out!

**Comment by rien** [comment]
It would be nice to have Zeus ID's here (and to apply this to other apps in the future as well) and also use those ID's as the primary way of authentication.

**Comment by niknetniko** [comment]
> It would be nice to have Zeus ID's here (and to apply this to other apps in the future as well) and also use those ID's as the primary way of authentication.

I agree, but I think this is a bit out of scope for this issue. If/When we implement this, we'll probably need more changes than just the API (e.g. we might discard internal Tab ID's all together and just use the global Zeus ID as the primary key in Tab/Tap/...)

**Comment by TomNaessens** [comment]
This got merged by accident 😬 

See https://github.com/ZeusWPI/Tab/pull/99
